instrumentation:
    excludes:
        - test/**/*.*test.js
        - index.js
        - gulpfile.js
        - jsDocs/**/*
        - apiDocs/**/*
    include-all-sources: true
check:
    global:
        statements: 95
        lines: 95
        branches: 95
